id: P003138
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 2021-12-17 10:42:54.495507
source_metadata:
  id: bdr:W1KG3398
  title: སྟོང་ཕྲག་ཉི་ཤུ་ལྔ་པ་རྒྱན་གྱི་ཚིག་འགྲེལ
  author: ''
  volumes:
    dba0c3bf35aa437d93c67e4d6c091c4d:
      image_group_id: I1KG3478
      title: ''
      volume_number: 1
      total_pages: 1172
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
