id: I129313A3
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T12:09:29+00:00'
last_modified: '2022-06-07T17:51:06.728222+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG3398
  title: སྟོང་ཕྲག་ཉི་ཤུ་ལྔ་པ་རྒྱན་གྱི་ཚིག་འགྲེལ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    A6AE:
      image_group_id: I1KG3478
      title: ''
      total_pages: 1172
      order: 1
      base_file: A6AE.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
